---
title: "Introduction to R for Cancer Scientists"
---

# Introduction

This site contains the materials for an R course run by the Bioinformatics Core
at the Cancer Research UK Cambridge Institute.
(Contributions : Matthew Eldridge, Chandra Chilamakuri, Mark Fernandes, Ashley Sawle, Kamal Kishore, Sergio Martinez Cuesta, Rory Stark)

October 2021

### Instructors

* Chandra Chilamakuri
* Mark Fernandes

# Description

**R** is one of the leading programming languages in **Data Science** and the
most widely used within CRUK CI for interacting with, analyzing and visualizing
cancer biology datasets.

In this training course, we aim to provide a friendly introduction to R pitched
at a beginners level but also for those who have been on R training courses
previously and would like a refresher or to consolidate their skills.

The course will be run over **5 sessions** with the following structure:

* **Lesson each day lasting 45 minutes
    * the instructor will share his/her screen featuring an RStudio window during this call
* More **in-depth material** covering the concepts introduced in the lesson to go through in your own time
* An **assignment** consisting of exercises to practice some of the concepts covered in that and previous lessons


# Schedule

0. [Getting set up](week0.html) (6 April) - installing R and RStudio

1. [Introduction to R](week1.html) (14 April) - Interacting with R using RStudio and introducing objects, data types and functions

2. [Working with data](week2.html) (20 April) - Creating R scripts, working with tabular data and other types of objects in R, reading data into R

3. [Data visualization with ggplot2](week3.html) (27 April) - A common grammar to create scatter plots, bar charts, boxplots, histograms and line graphs for time series data

4. [Data manipulation using dplyr](week4.html) (4 May) - Filtering and modifying tabular data, computing summary values, faceting with ggplot2

5. [Grouping and combining data](week5.html) (11 May) - Advanced grouping and summarization operations, joining data from different tables, customizing ggplot2 plots

6. [Restructuring data for analysis](week6.html) (18 May) - The concept of 'tidy data', pivoting and separating operations, ggplot2 extras

7. **Capstone project** – putting it all together in a typical data analysis including:

    * reading in a data set

    * handling missing values

    * selecting and filtering subsets of interest

    * creating plots

    * generating summary statistics

    * saving data transformed into a tidy format as a csv file for later analysis
