
---
title: "Assignment 1"
---


### Working with data from an Excel spreadsheet

**Read into R one of your own Excel spreadsheets and explore the data using `summary()`, `table()` and/or `plot()`**

We haven't yet showed how to read Excel spreadsheets into R. There are several package providing this capability but for this exercise use the `readxl` package
from the tidyverse.

`readxl` should have been installed as part of the tidyverse but if you find
that's not the case, you will have to install it separately.

`readxl` is not loaded as one of the core tidyverse packages when you run
`library(tidyverse)` so you'll have to load this separately.

If you don't have an Excel spreadsheet to hand, you can use the clinical
annotation data for the NCI-60 cell line data set (https://bioinformatics-core-shared-training.github.io/r-intro/data/cellline_nci60_clinical_data.xlsx).

```{r}

```

---

### Create a report for your assignment

Click on the 'Knit' menu at the top of this file and select either whichever
option you prefer to create an HTML, PDF or Word document version of your
assignment. This will run all the code chunks and "knit" the resulting
results with the surrounding text to produce a report.

#### Additional markdown features

**_Emphasis_**

Can use either underscores or asterisks and combination of both for both bold
and italic emphasis.

```
*italic*   **bold**
_italic_   __bold__
```

**_Inline Code_**

Use of backticks (`).

```
`mean(starwar$height)`
```

**_Horizontal Rule_**

Three of more asterisks or dashes.

```
*******

-------
```

**_Plain Code Blocks_**

Plain code blocks are displayed in a fixed-width font but not evaluated.

```
This text is displayed verbatim / preformatted
```

Have a look at examples of these in the text parts of this R markdown document
and how these are rendered when you run the knit operation.

For more features, see the help page in RStudio that can be accessed from the
the help menu: **Help > Markdown Quick Reference**.

